version: '3.8'

services:
  backend:
    image: visualizador-backend
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    depends_on:
      - db

  frontend:
    image: visualizador-frontend
    ports:
      - "3000:80"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: visualizador
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ~/.n8n:/home/node/.n8n
    env_file:
      - ../.env
    restart: unless-stopped

volumes:
  db-data:
